include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # avoid_print: false
    # prefer_single_quotes: true

formatter:
  # The page_width property is now correctly a top-level key
  page_width: 60