

default_platform(:android)

platform :android do
  desc "Lane for android Firebase app distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
    app: "1:967198046667:android:4d4505b25c075629ef1e4e",
    firebase_cli_token:"1//03n_THnc6Hhl7CgYIARAAGAMSNwF-L9Ir4b3vUvHM1RAudtwkH6_eoG_VaaRogjVd-f0b-WUddOPsKCEjT6xyL5Dgy4rh33ettSA",
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    testers: "sasa.bas38@gmail.com",
    release_notes: "New version available. Please update the app to the latest version."
  )
  end

  
end
